image:
  name: circleci/python:3.8-buster

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
  BUILDKIT_PROGRESS: plain
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
 
services:
  - docker:dind

lint_build_test:
  script:
    - docker version
    - docker-compose version
    - pip3 install pre-commit==2.8.2
    - pre-commit install --install-hooks
    - pre-commit run -a
    - ./build_and_test.sh
