version: '3.8'

services:
    nginx:
        build: nginx/
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ssl:/etc/letsencrypt
            - ssl:/var/www/certbot

    certbot:
        container_name: ${USER}-mb-certbot
        build: certbot/
        restart: unless-stopped
        depends_on:
            - nginx
        env_file:
            - .env
        volumes:
            - ssl:/etc/letsencrypt
            - ssl:/var/www/certbot

    cron:
        container_name: ${USER}-mb-cron
        build:
            context: cron/
            args:
                - WEB_IMAGE=${MB_REGISTRY_URL}dev/mb-web:${MB_WEB_TAG:-latest}
        depends_on:
            - web
        env_file:
            - .env

volumes:
    ssl:
        name: ${USER}-ssl
